# DO NOT EDIT
#
# GENERATED BY: Inline::Module 0.26

use strict; use warnings;
package Statistics::NiceR::DataConvert::PDL::Inline;
use base 'DynaLoader';
bootstrap Statistics::NiceR::DataConvert::PDL::Inline;

1;
